### ISSUE TITLE
Use of uninitialized value $1 in split

### ISSUE THREAD

**Issue by vadirajks** [RTBHOUSE/check_naglio_aerospike#1]
Thanks for nice script and do please let me know how to fix this below error. Thanks
Use of uninitialized value $1 in split at ./check_naglio_aerospike_namespace.pl line 2075.
CRITICAL: hwm-breached data is missing, stop-writes data is missing, available-bin-names data is missing, available_pct data is missing, evicted-objects_rate_ps data is missing, free-pct-disk data is missing, free-pct-memory data is missing

**Comment by mgrzybowski** [comment]
Hi  Vadirajks 
   Please check current version . It should be fixed . As from version 3.9 of the aerospike there was  Statistic/Benchmark/Logging Revamp . Some stats may have diffrent names .

## 

   Kind Regards
      Marek Grzybowski
